# Generated by Django 4.2.7 on 2026-08-27 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='owner_documents/identity/')),
                ('proof_of_ownership', models.FileField(blank=True, null=True, upload_to='owner_documents/proof/')),
                ('tax_identification', models.FileField(blank=True, null=True, upload_to='owner_documents/tax/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
