# Generated by Django 4.2.7 on 2026-08-27 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerverification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Vérification propriétaire', 'verbose_name_plural': 'Vérifications propriétaires'},
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name="Notes de l'administrateur"),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='owner_documents/identity/', verbose_name="Pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='proof_of_ownership',
            field=models.FileField(blank=True, null=True, upload_to='owner_documents/proof/', verbose_name='Justificatif de propriété'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='tax_identification',
            field=models.FileField(blank=True, null=True, upload_to='owner_documents/tax/', verbose_name="Pièce d'identification fiscale"),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verification', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
