# Generated by Django 4.2.7 on 2026-09-07 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_ownerverification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerverification',
            options={},
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='owner_documents/identity/'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='proof_of_ownership',
            field=models.FileField(blank=True, null=True, upload_to='owner_documents/proof/'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='tax_identification',
            field=models.FileField(blank=True, null=True, upload_to='owner_documents/tax/'),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
