# Generated by Django 4.2.7 on 2026-09-25 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_userprofile_phone_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_review', "En cours d'examen"), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], db_index=True, default='pending', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, help_text='Pourquoi souhaitez-vous devenir propriétaire ?')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_owner_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
