# Generated by Django 4.2.7 on 2026-08-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('property_validation', 'Validation annonce'), ('property_rejection', 'Rejet annonce'), ('new_property', 'Nouvelle annonce'), ('booking_request', 'Demande réservation'), ('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée'), ('owner_verification', 'Vérification propriétaire'), ('availability_reminder', 'Rappel disponibilité'), ('new_message', 'Nouveau message'), ('incident_report', 'Signalement'), ('system', 'Notification système')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
